### ISSUE TITLE
Adaptive scaling doesn't work with distributed 2.4

### ISSUE THREAD

**Issue by andersy005** [dask/dask-jobqueue#339]
I recently updated my dask and distributed versions to the latest versions (2.4). When I try using adaptive scaling,  `cluster.adapt()` seems to be broken. Am I missing something or is this a known issue?

```python
In [1]: from dask_jobqueue import PBSCluster

In [2]: cluster = PBSCluster()

In [3]: print(cluster.job_script())
#!/usr/bin/env bash

#PBS -N dask-worker
#PBS -q medium
#PBS -l nodes=1:ppn=48
#PBS -l walltime=08:00:00
#PBS -e /scratch/cluster/abanihi/
#PBS -o /scratch/cluster/abanihi/
#PBS -r n
JOB_ID=${PBS_JOBID%%.*}



/project/oce/abanihi/miniconda/envs/python-tutorial/bin/python -m distributed.cli.dask_worker tcp://128.117.124.150:43715 --nthreads 48 --memory-limit 96.00GB --name dask-worker--${JOB_ID}-- --death-timeout 60 --local-directory None


In [4]: cluster.adapt(minimum=1, maximum=2)
Out[4]: <distributed.deploy.adaptive.Adaptive at 0x7fc9d6ed47f0>

In [5]: tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fca1c507780>>, <Task finished coro=<AdaptiveCore.adapt() done, defined at /project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py:170> exception=AttributeError("'PBSCluster' object has no attribute 'plan'")>)
Traceback (most recent call last):
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py", line 182, in adapt
    recommendations = await self.recommendations(target)
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py", line 133, in recommendations
    plan = self.plan
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive.py", line 101, in plan
    return self.cluster.plan
AttributeError: 'PBSCluster' object has no attribute 'plan'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fca1c507780>>, <Task finished coro=<AdaptiveCore.adapt() done, defined at /project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py:170> exception=AttributeError("'PBSCluster' object has no attribute 'plan'")>)
Traceback (most recent call last):
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py", line 182, in adapt
    recommendations = await self.recommendations(target)
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py", line 133, in recommendations
    plan = self.plan
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive.py", line 101, in plan
    return self.cluster.plan
AttributeError: 'PBSCluster' object has no attribute 'plan'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fca1c507780>>, <Task finished coro=<AdaptiveCore.adapt() done, defined at /project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py:170> exception=AttributeError("'PBSCluster' object has no attribute 'plan'")>)
Traceback (most recent call last):
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py", line 182, in adapt
    recommendations = await self.recommendations(target)
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive_core.py", line 133, in recommendations
    plan = self.plan
  File "/project/oce/abanihi/miniconda/envs/python-tutorial/lib/python3.7/site-packages/distributed/deploy/adaptive.py", line 101, in plan
    return self.cluster.plan
```

```bash
(python-tutorial) -bash-4.2$ conda list dask
# packages in environment at /project/oce/abanihi/miniconda/envs/python-tutorial:
#
# Name                    Version                   Build  Channel
dask                      2.4.0                      py_0    conda-forge
dask-core                 2.4.0                      py_0    conda-forge
dask-jobqueue             0.6.3                      py_0    conda-forge
dask-mpi                  2.0.0                    py37_0    conda-forge
```

```bash
(python-tutorial) -bash-4.2$ conda list distributed
# packages in environment at /project/oce/abanihi/miniconda/envs/python-tutorial:
#
# Name                    Version                   Build  Channel
distributed               2.4.0                      py_0    conda-forge
```

Cc @mrocklin

**Comment by andersy005** [comment]
I can confirm that everything seems to be work with `distributed==2.3`

```python
In [1]: from dask_jobqueue import PBSCluster

In [2]: cluster = PBSCluster()

In [3]: cluster.adapt(minimum=1, maximum=2)
Out[3]: <distributed.deploy.adaptive.Adaptive at 0x7f6e3486fa90>

In [4]: cluster
Out[4]: PBSCluster(cores=0, memory=0 B, workers=0/1, jobs=0/1)

In [5]: cluster
Out[5]: PBSCluster(cores=0, memory=0 B, workers=0/1, jobs=0/1)

In [6]: cluster
Out[6]: PBSCluster(cores=0, memory=0 B, workers=0/1, jobs=0/1)

In [7]: cluster
Out[7]: PBSCluster(cores=0, memory=0 B, workers=0/1, jobs=0/1)

In [8]: !qstat -u $USER
                                                            Req'd  Req'd   Elap
Job ID          Username Queue    Jobname    SessID NDS TSK Memory Time  S Time
--------------- -------- -------- ---------- ------ --- --- ------ ----- - -----
8428981.chadmin abanihi  regular  dask-worke  55430   1  36  109gb 01:00 R 00:00

In [9]: cluster
Out[9]: PBSCluster(cores=36, memory=109.00 GB, workers=1/1, jobs=1/1)
```

```bash
abanihi@cheyenne2:~> conda list dask
# packages in environment at /glade/work/abanihi/softwares/miniconda3/envs/python-tutorial:
#
# Name                    Version                   Build  Channel
dask                      2.3.0                      py_0    conda-forge
dask-core                 2.3.0                      py_0    conda-forge
dask-jobqueue             0.6.3                      py_0    conda-forge
dask-mpi                  2.0.0                    py37_0    conda-forge
abanihi@cheyenne2:~> conda list distributed
# packages in environment at /glade/work/abanihi/softwares/miniconda3/envs/python-tutorial:
#
# Name                    Version                   Build  Channel
distributed               2.3.2                      py_1    conda-forge
```

**Comment by mrocklin** [comment]
Interesting.  Yeah, this is my fault.  It looks like the new adaptive code doesn't work well with the non-SpecCluster aware cluster managers. I should have made things more robust to older versions.

Some options:

1.  We can make things more consistent, and issue a bugfix release for distributed (this is probably the most mature solution)
2.  We can merge and release dask-jobqueue with the spec-rewrite branch (which seems close to being merged).  We should also check in with dask-kubernetes, which I suspect has similar issues, and is in a similar state of rewriting.  In the meantime, people would avoid the newest version.

I'll take a look at 1 tomorrow and see how expensive it would be.  In the meantime @andersy005 if you feel like looking at and testing https://github.com/dask/dask-jobqueue/pull/307 that would be welcome.

**Comment by andersy005** [comment]
Thank you for the update, @mrocklin! 

> In the meantime @andersy005 if you feel like looking at and testing #307 that would be welcome.

I will take look at it, and will report back if anything else is broken :)

**Comment by andersy005** [comment]
Appears to have been fixed in distributed >=2.5
